version: '3.8'

volumes:
  app_config:
  nginx_config:
  db_data:


services:
  # 1. 資料庫
  db:
    image: docker.io/library/postgres:15-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data:Z
    environment:
      POSTGRES_DB: accounting
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  # 2. 後端 (Django)
  backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app:Z
      - ./backend/media:/app/media:Z
      - /app/.venv
      - app_config:/app/config:Z
      - nginx_config:/app/nginx_shared:Z
    environment:
      DB_HOST: db
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${DJANGO_SECRET}
    depends_on:
      - db

  # 3. Nginx
  nginx:
    image: docker.io/library/nginx:alpine
    restart: always
    entrypoint: [ "/bin/sh", "/etc/nginx/entrypoint.sh" ]
    ports:
      - "8080:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./backend/media:/usr/share/nginx/html/media:ro
      - nginx_config:/etc/nginx/conf.d:Z
      - ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh:ro
    depends_on:
      - backend

  # 4. Cloudflare Tunnel
  tunnel:
    image: docker.io/cloudflare/cloudflared:latest
    restart: always
    entrypoint: [ "/bin/sh", "/etc/cloudflared/entrypoint.sh" ]
    volumes:
      - app_config:/etc/cloudflared/config:Z
      - ./tunnel/entrypoint.sh:/etc/cloudflared/entrypoint.sh:ro
